# Generated by Django 5.1.6 on 2025-03-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0003_women_delete_entry_delete_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="women",
            options={"ordering": ["-time_create"]},
        ),
        migrations.AddField(
            model_name="women",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255),
        ),
        migrations.AddIndex(
            model_name="women",
            index=models.Index(
                fields=["-time_create"], name="learning_lo_time_cr_e46a04_idx"
            ),
        ),
    ]
