# Generated by Django 5.1.6 on 2025-03-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0008_alter_women_cat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
