# Generated by Django 5.1.6 on 2025-03-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0011_husband_women_husband"),
    ]

    operations = [
        migrations.AlterField(
            model_name="husband",
            name="age",
            field=models.IntegerField(null=True),
        ),
    ]
