# Generated by Django 5.1.6 on 2025-03-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0012_alter_husband_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="husband",
            name="m_count",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
