# Generated by Django 5.1.6 on 2025-03-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0016_women_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="women",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d/",
                verbose_name="Фото",
            ),
        ),
    ]
